### ISSUE TITLE
STORE: Invalid opcode definition

### ISSUE THREAD

**Issue by tk-codes** [bazo-blockchain/bazo-vm#2]
In the BA-Documentation and [OpCode definition](https://github.com/bazo-blockchain/bazo-vm/blob/master/vm/op_codes.go#L101), it states that `STORE` doesn't need any argument.

However, after debugging it turns out to be that it does require an argument (store index).
https://github.com/bazo-blockchain/bazo-vm/blob/master/vm/vm.go#L574

There was no unit testing for this opcode either.

**Comment by skas102** [comment]
It takes an argument (address). Maybe we should only update the doc? 

See code snippet below:

```		
case StoreLoc:
	address, errArgs := vm.fetch(opCode.Name)
	right, errStack := vm.PopSignedBigInt(opCode)

	if !vm.checkErrors(opCode.Name, errArgs, errStack) {
		return false
	}

	callstackTos, err := vm.callStack.Peek()

	if err != nil {
		vm.evaluationStack.Push([]byte(opCode.Name + ": " + err.Error()))
		return false
	}

	callstackTos.variables[int(address)] = right
```

Otherwise I might missunderstood what you were describing. Please clarify in this case. @tk-codes

Test Cases are missing, and need to be defined, that's correct!
