### ISSUE TITLE
ArrInsert does not work for last index

### ISSUE THREAD

**Issue by tk-codes** [bazo-blockchain/bazo-vm#31]
For last index (size - 1), `ArrInsert` does not work.

```
code := []byte{
		Push, 2, 0x00, 0x02, // new value 2
		Push, 2, 0x00, 0x00, // index 0

		Push, 2, 0xFF, 0x00, // initial value 255
		NewArr,
		ArrAppend,
		ArrInsert, // Replace 255 with the new value 2
		Halt,
	}
```

Reason: ArrInsert removes the value at the given index. Then array size is decremented by 1. 
If the index is greater than array size, `goToIndex` function doesn't work. Therefore, the insert fails.

**Comment by skas102** [comment]
Fixed in https://github.com/bazo-blockchain/bazo-vm/pull/42
