### ISSUE TITLE
Separate evaluation stack for function call

### ISSUE THREAD

**Issue by tk-codes** [bazo-blockchain/bazo-vm#33]
At the moment, VM uses one evaluation stack for all.
When a function is called, it should work on a separate evaluation stack or have restricted access.

When executing the following Lazo code, `ret` opcodes throws the following error: **Number of returned elements does not match** because it also sees `2` from previous evaluation stack.

```
contract Test{
    int x
    constructor() {
        x = 2 + test()
    }

    function int test() {
        return 1
    }
}
```

**Comment by skas102** [comment]
Instead of a seperate evaluation stack we can work with relative pointers.
