### ISSUE TITLE
LoadSt: Check contract variable changes

### ISSUE THREAD

**Issue by tk-codes** [bazo-blockchain/bazo-vm#4]
When a contract variable is assigned (`x=3`), it stores the changes in a separate array.
When loading the variable (SLOAD), it does not check the changes, but always return the value of the original contract variable. 

As a result, the following lazo code always returns 0.

```go
    int x

    function int test() {
       x = 3
       return x
    }
```

**Comment by skas102** [comment]
This does not belong here. Changes are private and part of the vm-context which is part of the bazo-miner. We need to recreate the issue there and solve it within this project. What do you think @tk-codes @tbocek ?

An alternative would be to move the vm-context to the bazo-vm. I'm not sure if the miner is the right place for it.

**Comment by tk-codes** [comment]
@rpfister102 Yes, it requires a `GetChanges` function in the bazo-miner, similar to `GetContractVariable`.

**protocol.Context in bazo-miner**
```
type Context struct {
	Account
	changes []Change
	FundsTx
}

func (c *Context) GetContractVariable(index int) ([]byte, error) {
	if index >= len(c.ContractVariables) || index < 0 {
		return []byte{}, errors.New("Index out of bounds")
	}
	variable := []byte(c.ContractVariables[index])
	cp := make([]byte, len(variable))
	copy(cp, variable)

	return cp, nil
}
```

Alternatively, we can also keep track of changes in the VM.

**Comment by skas102** [comment]
@tk-codes Let's keep it simple. I think we should add another parameter to the `GetContractVariable` function called `respectChanges` and modify the function so that it either returns the variable with respect to changes or not. What do you think?

**Comment by skas102** [comment]
Will be resolved in the miner:

https://github.com/bazo-blockchain/bazo-miner/issues/30
